// Generated by CoffeeScript 1.8.0

/*
 * User YuanXiangDong
 * Date 14-10-14
 * url parmas encode util
 */

(function() {
  var debug, dontNeedEncoding;

  debug = require('debug')('gama-search::utils::url_encode');

  dontNeedEncoding = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_.~';

  exports.encode = function(str) {
    var buf, char, i, j, jlen, out, s, _i, _j, _ref;
    out = [];
    for (i = _i = 0, _ref = str.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      char = str[i];
      if (dontNeedEncoding.indexOf(char) >= 0) {
        out.push(char);
      } else {
        buf = new Buffer(char).toString('hex').toUpperCase();
        jlen = buf.length / 2;
        for (j = _j = 0; 0 <= jlen ? _j < jlen : _j > jlen; j = 0 <= jlen ? ++_j : --_j) {
          out.push("%" + (buf.substring(j * 2, (j + 1) * 2)));
        }
      }
    }
    s = out.join('');
    return s;
  };

  exports.query2string = function(params) {
    var key, str, val;
    str = '';
    for (key in params) {
      val = params[key];
      str += "" + (exports.encode(key)) + "=" + (exports.encode(val)) + "&";
    }
    str = str.substring(0, str.length - 1);
    return str;
  };

  exports.query2query = function(params) {
    var key, p, val;
    p = {};
    for (key in params) {
      val = params[key];
      p[exports.encode(key)] = "" + (exports.encode(val));
    }
    return p;
  };

}).call(this);
