// Generated by CoffeeScript 1.8.0

/*
 * search 的测试类
 */

(function() {
  var SearchManager, async, con, config, debug, fieldName, model_name_1, model_name_2, mulitItem, options, owner_id_1, owner_id_2, search, should, singleItem, table_name;

  should = require('should');

  debug = require('debug')('gama-search::tests::search_test');

  config = require('./config');

  SearchManager = require('../search');

  async = require('async');


  /*
  action=push&Version=v2&AccessKeyId=$accessKeyId&Signature=$signature&
      SignatureMethod=HMAC-SHA1&Timestamp=$timestamp&SignatureVersion=1.0&
          SignatureNonce=$signatureNonce&
              items=[{"cmd": "ADD",
                  "fields":{
                      "id":"8dac2812baa0b2",
                          "title":"这里是一个标题",
                              "body":"这里是文档的详细内容"}}]"
   */


  /*
      @accessKeyId = searchOptions.accessKeyId
      @accessKeySecret = searchOptions.accessKeySecret
      @apiURL = searchOptions.apiURL || 'http://opensearch.aliyuncs.com'
      @version = searchOptions.version || 'v2'
      @format = searchOptions.format || 'json'
      @timeout = searchOptions.timeout || 3000
      @dataType = searchOptions.dataType || 'json'
       *@serverURL = urlUtil.resolve @apiURL, path.join(@version, 'api/')
      @serverURL = @apiURL
      @indexName = searchOptions.indexName || 'test'
      @signatureMethod = searchOptions.signatureMethod||'HMAC-SHA1'
      @signatureVersion = searchOptions.SignatureVersion || '1.0'
   */

  console.dir(config);

  con = config.openSearch || {};

  console.dir(con);

  options = {
    accessKeyId: con.accessKeyId,
    accessKeySecret: con.accessKeySecret,
    apiURL: con.host,
    indexName: con.appName,
    pageSize: con.pageSize,
    timeout: con.timeout
  };

  fieldName = 'search_name';

  table_name = 'main';

  owner_id_1 = 'GO2SIsP';

  owner_id_2 = 'FOtmGSC';

  model_name_1 = 'Animation';

  model_name_2 = 'Tilemap';

  search = new SearchManager(options);

  singleItem = [
    {
      id: '6gUxv34',
      owner_id: 'FOtmGSC',
      permalink: 'test1/test2',
      model_name: 'Animation',
      created_at: '2014-09-09T02:53:59.012Z',
      item: '{"id":"6gUxv34","model_name":"Animation","owner_id":"FOtmGSC","title":"0010.png","desc":"","compiled_assets":{},"tags":[]}'
    }
  ];

  mulitItem = [
    {
      id: '6gUxv34',
      owner_id: 'FOtmGSC',
      permalink: 'test1/test2',
      model_name: 'Animation',
      created_at: '2014-09-09T02:53:59.012Z',
      item: '{"id":"6gUxv34","model_name":"Animation","owner_id":"FOtmGSC","title":"0010.png","desc":"","compiled_assets":{},"tags":[]}'
    }, {
      id: 'CQ33vri',
      owner_id: 'FOtmGSC',
      permalink: 'test1/test2',
      model_name: 'Figure',
      created_at: '2014-09-09T04:46:12.646Z',
      item: '{"id":"CQ33vri","model_name":"Figure","owner_id":"FOtmGSC","title":"untitled","desc":"","compiled_assets":{},"tags":[],"poses":[{"name":"act","_id":"540e86142994e1090fd0e8f5","flips":[0,0,0,0,0,0,0,0],"animations":["","","","","","","",""]}]}'
    }, {
      id: 'IWGi3JC',
      owner_id: 'FOtmGSC',
      permalink: 'test1/test2',
      model_name: 'Figure',
      created_at: '2014-09-09T02:54:51.838Z',
      item: '{"id":"IWGi3JC","model_name":"Figure","owner_id":"FOtmGSC","title":"untitled","desc":"","compiled_assets":{},"tags":[],"poses":[{"name":"act","_id":"540e6bfba4cc02c705be7382","flips":[0,0,1,0,0,0,0,0],"animations":["96zRxm4","","96zRxm4","","","","",""]}]}'
    }, {
      id: '8OuLxgQ',
      owner_id: 'FOtmGSC',
      permalink: 'test1/test2',
      model_name: 'Tilemap',
      created_at: '2014-09-09T02:57:18.544Z',
      item: '{"id":"8OuLxgQ","model_name":"Tilemap","owner_id":"FOtmGSC","title":"XFjXLifh-tilemaps-3hLQqBp-source.jpg","desc":"","compiled_assets":{},"tags":[]}'
    }
  ];

  describe("search test", function() {
    before(function() {});
    return describe("delete tests", function() {
      return it('delete single', function(done) {
        return search.deleteByField("aid", ['950435714'], table_name, function(err, data) {
          console.error("error:" + err);
          console.dir(data);
          return done();
        });
      });
    });
  });

}).call(this);
