// Generated by CoffeeScript 1.8.0

/*
 * search 的测试类
 */

(function() {
  var SearchManager, con, config, debug, model_name_1, model_name_2, mulitItem, options, owner_id_1, owner_id_2, search, should, singleItem, table_name;

  should = require('should');

  debug = require('debug')('gama-search::tests::search_test');

  config = require('./config');

  SearchManager = require('../search');


  /*
  action=push&Version=v2&AccessKeyId=$accessKeyId&Signature=$signature&
      SignatureMethod=HMAC-SHA1&Timestamp=$timestamp&SignatureVersion=1.0&
          SignatureNonce=$signatureNonce&
              items=[{"cmd": "ADD",
                  "fields":{
                      "id":"8dac2812baa0b2",
                          "title":"这里是一个标题",
                              "body":"这里是文档的详细内容"}}]"
   */


  /*
      @accessKeyId = searchOptions.accessKeyId
      @accessKeySecret = searchOptions.accessKeySecret
      @apiURL = searchOptions.apiURL || 'http://opensearch.aliyuncs.com'
      @version = searchOptions.version || 'v2'
      @format = searchOptions.format || 'json'
      @timeout = searchOptions.timeout || 3000
      @dataType = searchOptions.dataType || 'json'
       *@serverURL = urlUtil.resolve @apiURL, path.join(@version, 'api/')
      @serverURL = @apiURL
      @indexName = searchOptions.indexName || 'test'
      @signatureMethod = searchOptions.signatureMethod||'HMAC-SHA1'
      @signatureVersion = searchOptions.SignatureVersion || '1.0'
   */

  con = config.opensearch || {};

  options = {
    accessKeyId: con.accessKeyId,
    accessKeySecret: con.accessKeySecret,
    apiURL: con.host,
    indexName: "gama_test3"
  };

  table_name = 'main';

  owner_id_1 = 'GO2SIsP';

  owner_id_2 = 'FOtmGSC';

  model_name_1 = 'Animation';

  model_name_2 = 'Tilemap';

  search = new SearchManager(options);

  singleItem = [
    {
      id: '6gUxv34',
      owner_id: 'FOtmGSC',
      permalink: 'test1/test2',
      model_name: 'Animation',
      created_at: '2014-09-09T02:53:59.012Z',
      item: '{"id":"6gUxv34","model_name":"Animation","owner_id":"FOtmGSC","title":"0010.png","desc":"","compiled_assets":{},"tags":[]}'
    }
  ];

  mulitItem = [
    {
      id: '6gUxv34',
      owner_id: 'FOtmGSC',
      permalink: 'test1/test2',
      model_name: 'Animation',
      created_at: '2014-09-09T02:53:59.012Z',
      item: '{"id":"6gUxv34","model_name":"Animation","owner_id":"FOtmGSC","title":"0010.png","desc":"","compiled_assets":{},"tags":[]}'
    }, {
      id: 'CQ33vri',
      owner_id: 'FOtmGSC',
      permalink: 'test1/test2',
      model_name: 'Figure',
      created_at: '2014-09-09T04:46:12.646Z',
      item: '{"id":"CQ33vri","model_name":"Figure","owner_id":"FOtmGSC","title":"untitled","desc":"","compiled_assets":{},"tags":[],"poses":[{"name":"act","_id":"540e86142994e1090fd0e8f5","flips":[0,0,0,0,0,0,0,0],"animations":["","","","","","","",""]}]}'
    }, {
      id: 'IWGi3JC',
      owner_id: 'FOtmGSC',
      permalink: 'test1/test2',
      model_name: 'Figure',
      created_at: '2014-09-09T02:54:51.838Z',
      item: '{"id":"IWGi3JC","model_name":"Figure","owner_id":"FOtmGSC","title":"untitled","desc":"","compiled_assets":{},"tags":[],"poses":[{"name":"act","_id":"540e6bfba4cc02c705be7382","flips":[0,0,1,0,0,0,0,0],"animations":["96zRxm4","","96zRxm4","","","","",""]}]}'
    }, {
      id: '8OuLxgQ',
      owner_id: 'FOtmGSC',
      permalink: 'test1/test2',
      model_name: 'Tilemap',
      created_at: '2014-09-09T02:57:18.544Z',
      item: '{"id":"8OuLxgQ","model_name":"Tilemap","owner_id":"FOtmGSC","title":"XFjXLifh-tilemaps-3hLQqBp-source.jpg","desc":"","compiled_assets":{},"tags":[]}'
    }
  ];

  describe("search test", function() {
    before(function() {});
    describe("insert tests", function() {
      it('insert single', function(done) {
        return search.insert(singleItem, table_name, function(err, data) {
          console.error("error:" + err);
          console.dir(data);
          return done();
        });
      });
      return it('insert mulit', function(done) {
        return search.insert(mulitItem, table_name, function(err, data) {
          console.error("error:" + err);
          console.dir(data);
          return done();
        });
      });
    });
    describe("update tests", function() {
      it('update single', function(done) {
        return search.update(singleItem, table_name, function(err, data) {
          console.error("error:" + err);
          console.dir(data);
          return done();
        });
      });
      return it('update mulit', function(done) {
        return search.update(mulitItem, table_name, function(err, data) {
          console.error("error:" + err);
          console.dir(data);
          return done();
        });
      });
    });
    return describe('search tests', function() {
      it("search default test", function(done) {
        return search.search('Tilemap', 'item', ['owner_id', owner_id_2, 'AND', 'model_name', model_name_2], 1, function(err, data) {
          console.error("error:" + err);
          console.dir(data);
          if ((data || {}).status === "OK") {
            console.dir(data.result);
          }
          return done();
        });
      });
      return it("advancedSearch tests", function(done) {
        var others, subQuerys;
        subQuerys = {
          filter: ['owner_id', owner_id_2, 'AND', 'model_name', model_name_2],
          aggregate: "group_key:model_name,agg_fun:count()"
        };
        others = {
          fetch_fields: ['id', 'model_name', 'item'],
          summary: "summary_field:item"
        };
        return search.advancedSearch('Tilemap', 'item', 1, subQuerys, others, function(err, data) {
          console.error("error:" + err);
          console.dir(data);
          if ((data || {}).status === "OK") {
            console.dir(data.result);
          }
          return done();
        });
      });
    });
  });

}).call(this);
